language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: EFXevtSS1FlB7tnxNa2cpkmqrR7bCdg7KeaHjaK4DTeK7kXUB7WIDcPENz6bjmOYVdGiw3bmc+RXTmLDSng3aWRVLVFaVA8YAnz9Wp2RWtVURWPJNByI4p3PYBwUhv1vj57PiT2XQv9qWweG+zfF7iOeARcGM8jbK4zEqP7j+FsZbQPEszEMtApGFeAFp4aI5Uzfx4MaGYI/8liAygIyz5P03sYBGHbZ3NlouauoV+tcA17J20op6PAxlH22ZnbWpiPG7jhzzqCXTJyX/2FSkBBZEWL+Z9HgS7rswPnpnFE0UeRDvsF22HUYleInWuYfpGD7c9DwBpg7pKmmWj441AuQGqAI+OYYEb5yBLf9p1SORlVdMvxIwsynaszhi+gjatXNKQwL2ZwCKHdisUucwl60ssPnqyhRb40JOsr7i94DwRHKJ6BkBT2iow3Z1iOo7WhYcve4y/sV0gmBEiuevlkQHL71QUAs4GA/Gu+ygzo5NZ8bNyiyfOXgyxSrt2gFq0bvuueuCw1C9PN5ZvWfbeHqz/tY9qixcqU7XG3L38CQnqeNSy1eGQ7XaAfmO/gUAKXgbeKyiosWjF8gbyd5k8OH+Kw1PvDfcXZZOyFO22wK/NSAN9Ngo1zTK0etPYyK1Wo7d4DPpEp+Yoz0yJdFWPRudHnhkpuw/FqnJ7zKYcA=
